---
title: "Frito Lay: Customer Attrition - KNN Modeling"
output: 
  github_document:
    html_preview: false
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,       
  warning = FALSE,   
  message = FALSE    
)
```

```{r}
library(tidyverse)
library(tidymodels)  
library(themis)
library(kknn)
library(naivebayes) 
library(caret)
set.seed(123)
```


--------------------------------------------------------------------------------------------------------------------------------------------------


### ------------ Data Loading -------------

```{r}
data <- read.csv("../data/CaseStudy1-data.csv")
```


--------------------------------------------------------------------------------------------------------------------------------------------------


### ------------ KNN Modeling -------------

```{r}
set.seed(123)

data$Attrition <- relevel(factor(data$Attrition), ref = "Yes")

idx   <- createDataPartition(data$Attrition, p = 0.7, list = FALSE)
train <- data[idx, ]
test  <- data[-idx, ]

attrition_rec <- recipe(Attrition ~ ., data = train) %>%
  step_string2factor(all_nominal_predictors()) %>%
  step_nzv(all_predictors()) %>%
  step_dummy(all_nominal_predictors(), one_hot = TRUE) %>%
  # step_corr(all_numeric_predictors(), threshold = 0.9) %>%
  # step_normalize(all_numeric_predictors(), -all_outcomes()) %>%
  step_range(all_numeric_predictors(), -all_outcomes(), min = 0, max = 1) %>% 
  step_tomek(Attrition) %>%
  step_upsample(Attrition, over_ratio = 1)

f1_summary <- function(data, lev = NULL, model = NULL) {
  precision <- posPredValue(data$pred, data$obs, positive = lev[1])
  recall    <- sensitivity(data$pred, data$obs, positive = lev[1])
  f1        <- (2 * precision * recall) / (precision + recall)

  c(F1 = f1)
}

ctrl <- trainControl(
  method = "cv",
  number = 10,
  summaryFunction = f1_summary,
  classProbs = FALSE,
  savePredictions = "final"
)

grid <- expand.grid(k = seq(3, 100, by = 3))

set.seed(42)

knn_model <- train(
  attrition_rec,
  data = train,
  method = "knn",
  trControl = ctrl,
  tuneGrid = grid,
  metric = "F1"
)

pred_test <- predict(knn_model, newdata = test)
confusionMatrix(pred_test, test$Attrition, positive = "Yes")
```


--------------------------------------------------------------------------------------------------------------------------------------------------


### ------------ KNN Feature Importance -------------

```{r}
importance_nb <- varImp(knn_model)
plot(importance_nb, top = 10, main = "Top 10 Feature Importances - K-Nearest Neighbors")
```



--------------------------------------------------------------------------------------------------------------------------------------------------


### ------------ Saving Model -------------

```{r}
# Save an R object
saveRDS(knn_model, "../models/knn_model.rds")
```

